# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class UpdateResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, example_response: object=None, annotations: List[str]=None):  # noqa: E501
        """UpdateResponse - a model defined in Swagger

        :param example_response: The example_response of this UpdateResponse.  # noqa: E501
        :type example_response: object
        :param annotations: The annotations of this UpdateResponse.  # noqa: E501
        :type annotations: List[str]
        """
        self.swagger_types = {
            'example_response': object,
            'annotations': List[str]
        }

        self.attribute_map = {
            'example_response': 'example_response',
            'annotations': 'annotations'
        }

        self._example_response = example_response
        self._annotations = annotations

    @classmethod
    def from_dict(cls, dikt) -> 'UpdateResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UpdateResponse of this UpdateResponse.  # noqa: E501
        :rtype: UpdateResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def example_response(self) -> object:
        """Gets the example_response of this UpdateResponse.


        :return: The example_response of this UpdateResponse.
        :rtype: object
        """
        return self._example_response

    @example_response.setter
    def example_response(self, example_response: object):
        """Sets the example_response of this UpdateResponse.


        :param example_response: The example_response of this UpdateResponse.
        :type example_response: object
        """

        self._example_response = example_response

    @property
    def annotations(self) -> List[str]:
        """Gets the annotations of this UpdateResponse.


        :return: The annotations of this UpdateResponse.
        :rtype: List[str]
        """
        return self._annotations

    @annotations.setter
    def annotations(self, annotations: List[str]):
        """Sets the annotations of this UpdateResponse.


        :param annotations: The annotations of this UpdateResponse.
        :type annotations: List[str]
        """

        self._annotations = annotations
